[server]
grpc_addr = ":4449"
tls_cert_file = "/fixtures/clientapi-server.crt"
tls_key_file = "/fixtures/clientapi-server.key"

[logging]
level = "debug"

[upstream]
addr = "https://notaryserver:4443"
